#ifndef LDX12_DEFINES_HLSLI
#define LDX12_DEFINES_HLSLI

#define LDX12_DESCRIPTOR_SLOT_INVALID 0u

#define LDX12_FREE_CBV_SLOT_FIRST 1u
#define LDX12_FREE_CBV_SLOT_COUNT 5u
#define LDX12_ENGINE_CBV_SLOT_FIRST 6u
#define LDX12_ENGINE_CBV_SLOT_COUNT 5u
#define LDX12_CBV_SLOT_COUNT 10u
#define LDX12_CBV_SLOT_LAST 10u

#define LDX12_CBV_SLOT_FREECB0 1u
#define LDX12_CBV_SLOT_FREECB1 2u
#define LDX12_CBV_SLOT_FREECB2 3u
#define LDX12_CBV_SLOT_FREECB3 4u
#define LDX12_CBV_SLOT_FREECB4 5u
#define LDX12_CBV_SLOT_ENGINE_FRAME 6u
#define LDX12_CBV_SLOT_ENGINE_CAMERA 7u
#define LDX12_CBV_SLOT_ENGINE_OBJECT 8u
#define LDX12_CBV_SLOT_ENGINE_MATERIAL 9u
#define LDX12_CBV_SLOT_ENGINE_LIGHTING 10u

#define LDX12_FREE_SRV_SLOT_FIRST 11u
#define LDX12_FREE_SRV_SLOT_COUNT 5u
#define LDX12_ENGINE_SRV_SLOT_FIRST 16u
#define LDX12_ENGINE_SRV_SLOT_COUNT 5u
#define LDX12_SRV_SLOT_COUNT 10u
#define LDX12_SRV_SLOT_LAST 20u

#define LDX12_SRV_SLOT_FREESRV0 11u
#define LDX12_SRV_SLOT_FREESRV1 12u
#define LDX12_SRV_SLOT_FREESRV2 13u
#define LDX12_SRV_SLOT_FREESRV3 14u
#define LDX12_SRV_SLOT_FREESRV4 15u
#define LDX12_SRV_SLOT_ENGINE_SCENE 16u
#define LDX12_SRV_SLOT_ENGINE_INSTANCES 17u
#define LDX12_SRV_SLOT_ENGINE_MATERIALS 18u
#define LDX12_SRV_SLOT_ENGINE_MESHES 19u
#define LDX12_SRV_SLOT_ENGINE_TEXTURES 20u

#define LDX12_FREE_RW_SLOT_FIRST 21u
#define LDX12_FREE_RW_SLOT_COUNT 3u
#define LDX12_ENGINE_RW_SLOT_FIRST 24u
#define LDX12_ENGINE_RW_SLOT_COUNT 2u
#define LDX12_RW_SLOT_COUNT 5u
#define LDX12_RW_SLOT_LAST 25u

#define LDX12_RW_SLOT_FREERW0 21u
#define LDX12_RW_SLOT_FREERW1 22u
#define LDX12_RW_SLOT_FREERW2 23u
#define LDX12_RW_SLOT_ENGINE_SCRATCH0 24u
#define LDX12_RW_SLOT_ENGINE_SCRATCH1 25u

#define LDX12_BINDLESS_FIXED_SLOT_FIRST 1u
#define LDX12_BINDLESS_FIXED_SLOT_LAST LDX12_RW_SLOT_LAST
#define LDX12_BINDLESS_DYNAMIC_SLOT_FIRST ( LDX12_BINDLESS_FIXED_SLOT_LAST + 1u )

#define LDX12_SAMPLER_SLOT_LINEAR_CLAMP 0u
#define LDX12_SAMPLER_SLOT_LINEAR_WRAP 1u
#define LDX12_SAMPLER_SLOT_POINT_CLAMP 2u
#define LDX12_SAMPLER_SLOT_SHADOW_COMPARISON 3u
#define LDX12_BUILT_IN_SAMPLER_COUNT 4u
#define LDX12_CUSTOM_SAMPLER_SLOT_FIRST LDX12_BUILT_IN_SAMPLER_COUNT
#define LDX12_CUSTOM_SAMPLER_COUNT 4u
#define LDX12_SAMPLER_COUNT 8u

#endif
