# Shared, target-local compiler policy. Third-party targets opt in explicitly.
function(ldx12_enable_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /EHsc /permissive- /MP)
    endif()
endfunction()

# One declaration owns an example that lives next to this call.
function(ldx12_add_example target output_name)
    cmake_parse_arguments(PARSE_ARGV 2 sample "" "FOLDER;LABEL" "SOURCES;ROOT_ASSETS;LIBRARIES")
    if(sample_UNPARSED_ARGUMENTS OR sample_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid arguments for example ${target}")
    endif()
    set(sources "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp")
    foreach(source IN LISTS sample_SOURCES)
        list(APPEND sources "${CMAKE_CURRENT_SOURCE_DIR}/${source}")
    endforeach()
    foreach(asset IN LISTS sample_ROOT_ASSETS)
        list(APPEND sources "${LDX12_PROJECT_ROOT}/${asset}")
    endforeach()
    foreach(source IN LISTS sources)
        if(source MATCHES "\\.(hlsl|hlsli|png)$")
            set_source_files_properties("${source}" PROPERTIES HEADER_FILE_ONLY TRUE)
        endif()
    endforeach()
    add_executable(${target} WIN32 ${sources})
    target_compile_features(${target} PRIVATE cxx_std_20)
    target_compile_definitions(${target} PRIVATE LDX12_MEDIA_DIRECTORY="${LDX12_PROJECT_ROOT}/media")
    target_link_libraries(${target} PRIVATE ${sample_LIBRARIES})
    ldx12_enable_warnings(${target})

    if(NOT sample_FOLDER)
        set(sample_FOLDER "examples")
    endif()
    if(NOT sample_LABEL)
        string(REGEX REPLACE "^([0-9]+)_" "\\1. " sample_LABEL "${target}")
    endif()
    set_target_properties(${target} PROPERTIES
        OUTPUT_NAME "${output_name}" PROJECT_LABEL "${sample_LABEL}" FOLDER "${sample_FOLDER}")
    source_group(TREE "${LDX12_PROJECT_ROOT}" FILES ${sources})
endfunction()
